[[main]] 
    identifier = "home"
    name = "首页"
    pageRef = "/"
    weight = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
    [main.params]
        icon = "archives"

[[main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 3
    [main.params]
        icon = "search"

[[main]]
    identifier = "links"
    name = "友情链接"
    url = "/links/"
    weight = 4
    [main.params]
        icon = "link"

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/w2343419-del"
    weight = 1
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://x.com/jdLSs0bK8671794"
    weight = 2
    [social.params]
        icon = "brand-twitter"

[[social]]
    identifier = "email"
    name = "邮箱"
    url = "mailto:w2343419@gmail.com"
    weight = 3
    [social.params]
        icon = "mail"
        newTab = false
